### ISSUE TITLE
Unable to verify SourceForge subdomain

### ISSUE THREAD

**Issue by joeraz** [flathub/website#1177]
Hello.  I attempted to run the verification process on my app.  However, it did not properly recognize the SourceForge subdomain that's the app's main website.

Though I uploaded the token file correctly to [appname].sourceforge.io, the verification process is not using the subdomain as part of the application URL, and is instead checking sourceforge.io directly, thus causing the verification to fail.  Can the verification check be updated to recognize the subdomains in the application URLs?

**Comment by pedrolcl** [comment]
Same here. I have 4 applications in Flathub hosted by Sourceforge:

* https://flathub.org/apps/net.sourceforge.VMPK
* https://flathub.org/apps/net.sourceforge.dmidiplayer
* https://flathub.org/apps/net.sourceforge.kmetronome
* https://flathub.org/apps/net.sourceforge.kmidimon

I am the author of all of them, and I am also the packager. But I can't verify any because in all cases this site requests to  put a file 'https://sourceforge.net/.well-known/org.flathub.VerifiedApps.txt' which I can't. That requires write access to the  root web domain of Sourceforge. I have a subdomain for each application, and I could put the file there, but this is not supported by Flathub:

* https://vmpk.sourceforge.net that redirects to https://vmpk.sourceforge.io
* https://dmidiplayer.sourceforge.net -> https://dmidiplayer.sourceforge.io
* https://kmetronome.sourceforge.net -> https://kmetronome.sourceforge.io
* https://kmidimon.sourceforge.net -> https://kmidimon.sourceforge.io

Please, enable a solution. Thanks.

**Comment by razzeee** [comment]
Should start working, as soon as the backend is redeployed

**Comment by joeraz** [comment]
Was able to verify.  Confirmed, thanks.
