### ISSUE TITLE
Old apps / stale apps categorized as "New Apps" or "Recently Updated Apps"

### ISSUE THREAD

**Issue by ifeeltiredboss** [flathub/website#1361]
1. [Bookworm](https://flathub.org/apps/com.github.babluboy.bookworm) - latest entry in Changelog is from 3 yrs ago, displayed in Recently Updated Apps, [video](https://user-images.githubusercontent.com/111905360/233781444-b06ad06f-91ea-4176-aaad-827fecdb1782.mov)
2. [Adobe Reader](https://flathub.org/apps/com.adobe.Reader) - latest entry in Changelog is from 10 yrs ago, displayed in New Apps, [video](https://user-images.githubusercontent.com/111905360/233781578-aceb04f6-228a-410c-ae2f-b8dc3c3c1148.mov)

Not really sure how to approach no. 2 because it is displayed as New App just because it was submitted to Flathub recently. However, it looks out of place imho :)

**Comment by puelp** [comment]
The first happens when a library or a runtime or something behind-the-scenes in the Flathub version/build was updated, even if the app itself hasn't been updated in years.

It's not really a functional error, but rather a cosmetic one. There should definitely be a message or something that informs users of that, instead of leaving them confused as @ifeeltiredboss was.

The second one is only a problem because the page is titled "New Apps". It should really be titled "Recently Added" as the URL (https://flathub.org/apps/collection/recently-added/1) already is.

**Comment by razzeee** [comment]
> The first happens when a library or a runtime or something behind-the-scenes in the Flathub version/build was updated, even if the app itself hasn't been updated in years.

It can also happen, when the app updates, but they don't put anything into the release metadata.

**Comment by razzeee** [comment]
The second one should be addressed by https://github.com/flathub/website/pull/1564

**Comment by razzeee** [comment]
I don't think there is much we can do on the website. It might be nice to add a build timestamp into the appstream, but that would have to happen in flat-manager or somewhere earlier in the stack.

I will close this here.
