### ISSUE TITLE
"My Flathub" button missing after login

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/website#1493]
It looks like that there is no "My Flathub" button/link displayed on the Flathub website after logging in and there is no easy way to find the My Flathub page (https://flathub.org/en/my-flathub).

![header-buttons](https://github.com/flathub/website/assets/2339930/de0564ab-05a5-4ab9-a384-316c4a207a02)

**Comment by razzeee** [comment]
Do you have a white avatar maybe? Is there really nothing to click?

**Comment by AsciiWolf** [comment]
It looks like there is nothing to click.

**Comment by razzeee** [comment]
Not sure what to do.

Can you try different browsers?
Can you try inspecting the html at that place?
Can you tell us with which provider you logged in?
Can you show us the avatar your using on that provider?

**Comment by razzeee** [comment]
Were you able to test this further?

**Comment by AsciiWolf** [comment]
I have tried it in Chromium instead of Firefox and had the same issue.

I have also tried copying and pasting the whole index html source from a Flathub.org page opened in an anonymous window into a text file and comparing it with the same html source from my session where I am logged in (using the GitHub provider) and the "Login" button is hidden. Both the source files were identic, with no changes.

**Comment by razzeee** [comment]
The login button should be hidden, if you're logged in.

**Comment by razzeee** [comment]
I assume the browsers you tried with had no addons installed?

**Comment by AsciiWolf** [comment]
Yep, clean Chromium profile, no addons or any user data.

**Comment by Lesik** [comment]
I can reproduce this with GitHub login. I noticed that the profile dropdown is indeed there in the DOM, but not visible because it contains only sr-text and no avatar. The avatar is [not rendering when `userName` prop is empty](https://github.com/flathub/website/blob/27e60f144bc8001b04a511787162f1dde263f99c/frontend/src/components/user/Avatar.tsx#L17-L19), which is taken from the [`info.displayname` field](https://github.com/flathub/website/blob/05770cf1f52a4168610ea6eef79fe5a6d0db4900/frontend/src/components/layout/Header.tsx#L293-L296) of `UserContext`. Upon inspection of the UserContext in my browser, `displayname` is null. So that's what causes the visual part of this issue.

The `displayname` is coming from this part of the endpoint:

https://github.com/flathub/website/blob/27e60f144bc8001b04a511787162f1dde263f99c/backend/app/logins.py#L911-L916

I believe this is the place where `display_name` is set on the user (only on user creation, as #1497 points out):

https://github.com/flathub/website/blob/27e60f144bc8001b04a511787162f1dde263f99c/backend/app/logins.py#L835-L836

In case of GitHub, the `provider_data` is returned by this function, which uses the GitHub API wrapper:

https://github.com/flathub/website/blob/05770cf1f52a4168610ea6eef79fe5a6d0db4900/backend/app/logins.py#L474-L482

So the empty name must be coming from the GitHub API directly. It makes sense, if you look at the profiles of the affected users (@AsciiWolf and @Lesik), you will find that we don't have a "full name" set like @razzeee does, instead our profiles just show our usernames.

An easy solution would be to just use the `login` instead of `name` when `name` is returned empty from the API:

```py
user = models.FlathubUser(display_name=provider_data["name"] or provider_data["login"])
```

Unfortunately, as #1497 pointed out, the `display_name` is only set on first login, and never updated afterwards, so even with this fix, all users who are currently facing this bug, will continue to face it. What would be the preferred approach here?

**Comment by razzeee** [comment]
The column for `display_name` is explicitly setup to be nullable.

```
sa.Column("display_name", sa.String(), nullable=True),
```

So I guess that's something the backend should be fine with. In that case, we could probably figure out a sane way to handle it in the frontend.

**Comment by Lesik** [comment]
What I'm just wondering is whether it's weird that these people won't be referred to by anything person-related at all. It's not that they don't have a name, they do, their username. If they signed up for GitHub a while ago, they might not even be aware that there's a new "full name" field in their GitHub profile that is currently empty (I wasn't). Or they do, but just be more comfortable that way. They would expect for all intents and purposes to be simply referred to by their username.
