### ISSUE TITLE
Should "downloads over time" graphs be reduced to past few months? (and general graphs gripes)

### ISSUE THREAD

**Issue by barthalion** [flathub/website#16]
1. For applications that are available on Flathub for a long time, the graph does not seem very useful right now, as there were fewer downloads in the past than now. As these numbers aren't very indicative of anything (as we don't track machine-id or IPs), would it make sense to limit them to past few months, 3, 6 or 12?

![image](https://user-images.githubusercontent.com/380403/153628820-4b81012b-d4e2-4d2a-ac35-ed4bff1ee8ee.png)

~2. The spikes in the graph above are most likely caused by updates. Should we graph only downloads with updates subtracted, to flatten it a bit? Alternatively, should we apply some "weight" to make the graph appear less suspicious?~ This is done now thanks to Kolja.

3. In the past, we haven't agreed on displaying graphs at all to avoid disappointing new developers that their applications aren't very popular (more or less). Not sure if that's something we want to stick to for new submissions.

cc @nedrichards

**Comment by tchx84** [comment]
> Personally, I think the shorter span is much more readable. The PR above makes it possible to request different number of days, so we could offer alternative views if needed.

+1

In general, as one app developer, I am interested in trends, e.g. did my last release increased the number of installations over time?

**Comment by jurf** [comment]
I think it is much more readable this way, and much more understandable for users, as they can compare graphs more easily between apps. However, I see no reason why not to include an ‘All time’ button which would display the whole thing.

One user story I have not seen mentioned is ‘As a user, I want to see how many people currently use an app, so that I can use this information when choosing between alternatives’. To me, the active users stat is just superior, and it does not really need a graph.

**Comment by razzeee** [comment]
I don't think that data exists or should exist. There are Download stats, which should be a helpful guidance

**Comment by jurf** [comment]
It should not be hard to heuristically infer it from the number of update downloads after an update comes out. It would necessarily not be exact, but that is not important anyway.

**Comment by razzeee** [comment]
I think this issue is done and we should create new ones for changes/additions. Closing.
