### ISSUE TITLE
Add light/dark theme toggle

### ISSUE THREAD

**Issue by quinzee33** [flathub/website#174]
I think it would be useful to do as many other sites have done and add a light/dark theme toggle override.

I did a very poor gimp edit showing an example of what I mean:
![dark_theme_toggle](https://user-images.githubusercontent.com/101351551/165880910-1b616241-c72d-4390-82b9-ce6f7247c749.png)
![light_theme_toggle](https://user-images.githubusercontent.com/101351551/165880915-8d738466-d674-4709-b410-4555a3817848.png)

**Comment by razzeee** [comment]
I really don't want to sacrifice header space for that (and personally I think those things are worthless). I think most sites do this, as they don't correctly detect the current theme of a user, which we do. And all major OS have these theme support now.

**Comment by kymckay** [comment]
The UX discussion I've read about this before would suggest the idea is to accommodate users who may not want the site to match their system theme.

I'd agree if this was to be added it probably isn't worth putting straight into the header

**Comment by Danik1601** [comment]
> I really don't want to sacrifice header space for that (and personally I think those things are worthless). I think most sites do this, as they don't correctly detect the current theme of a user, which we do. And all major OS have these theme support now.

Whatever you do just don't remove that automatic detection option (if you are ever going to add an override option or something), please.
There is (or maybe it was) a trend of misunderstanding the whole dark/light theme concept. Instead of switching on sunset/sunrise and quick toggle option, some companies consider dark/light theme as a static customization feature. OnePlus did it until Android 11, macOS did until 10.15, Windows does it right now and really makes me mad. So whatever you do with a dark/light theme please, please, please don't break that sweet automatic detection like many others do

**Comment by razzeee** [comment]
I'll close this, as I don't think this will happen.

**Comment by Miepee** [comment]
Older issue, but I'd also like a *manual* theme toggle. Not necessarily in the header bar, but somewhere would be nice.

**Comment by Francewhoa** [comment]
For those facing a challenge with the automated detection of your OS theme failed. I suggest this free and open source add-on. Which is both free and Libre Source (Open Source) at https://darkreader.org
