### ISSUE TITLE
No manual dark mode setting on website

### ISSUE THREAD

**Issue by s-20** [flathub/website#1819]
Or maybe I'm just missing it. There doesn't appear to be a way to manually set dark mode (or light mode for that matter) that I can see. I guess it's not a big deal, but it is annoying.

**Comment by razzeee** [comment]
That's intended

**Comment by Atemo-C** [comment]
This is a bit of an "old" issue, but one I keep being lead to. Why not provide an option, though? “That's intended” is as good as a reason as none if it is not explained **why** this is intended, and I struggle to see why it is, if not for the most simplicity's sake.

One of the problems, but in my experience the *main* one, is that because of some browsers, some settings, and other variables, Flathub uses a mode that is not adapted to the user's preference, and a user cannot currently switch to the opposite mode without the use of external browsers add-ons or other strange shenanigans, stuck with whichever one Flathub.org provides, unless they completely change their browser or some system settings. I need not say why that is undesirable, at best.

I understand that this is really more of a global issue with fragmentation between browsers, their settings, and more, and as much as I would like it to “just work” like it's intended to, it is unfortunately, just like most things in modern tech, broken. This is one of the reason that a lot of popular websites/web apps with both a light and dark mode have a toggle for them *(even if some lock this option behind an account wall, which is stupid, but not the subject of this comment)*.

As it stands, I currently have to use an external extension like Dark Reader to modify the global theming of the website, but it breaks things such as the logo and other elements, no longer having the correct contrast or not being the correct elements, and others. I am considering using another add-on that lets me dynamically change a website's CSS attributes, but I should not have to. On the opposite side, a friend of mine on his phone cannot switch to the light mode, which he prefers.

I personally struggle a lot more to read black text on white, and some struggle with the opposite. It would be great for accessibility purposes and user choice to have at least a toggle, and not be stuck with whichever default is used.

I dearly hope that this decision will be re-considered in the future.

**Comment by s-20** [comment]
I also find it much ewasier to read light on dark when I'm using a monitor. The brightness makes it hard on my eyes to keep staring at it for long enough to read.

The reason I think it should be available as a manual switch is a fingerprinting and privacy issue. I can't turn off theming to limit my fingerprint *and* use bright websites where I'll have to read. I was on a security kick at the time I made the original post, but the issue still stands. Your website doesn't need to know what my browser/desktop (or whatever) theme is, and it's weird that a site devoted to linux can't make that one small concession.

**Comment by razzeee** [comment]
You can edit the Html to switch to dark mode, it's one of the first tags on the site. That should be best from a fingerprinting pov.

**Comment by Atemo-C** [comment]
> You can edit the Html to switch to dark mode, it's one of the first tags on the site. That should be best from a fingerprinting pov.

Fingerprinting reasons for more advanced/privacy-minded users aside, an average user should never be expected to edit a website's HTML or CSS to choose a setting that could have a manual option somewhere on the website itself. Furthermore, that "solution" is not viable on all devices/browsers, too, especially on more restrictive platforms, such as many mobile devices. Even if this would not be a problem, one should still not have to do it.

This is, especially in terms of accessibility and user-friendliness, quite bad, and at the end of the day, the issue still stands; The actual solution, to me, seems quite straight forward *(adding a user-facing option on the website, wherever it may be)*, and I really want to know why not having it is “expected”. I would *probably* not agree with the reasoning, but I could at least understand if it would be explained.

**Comment by s-20** [comment]
> You can edit the Html to switch to dark mode, it's one of the first tags on the site. That should be best from a fingerprinting pov.

Your solution to a accessibility/privacy issue is *edit the HTML*? I genuinely don't know how to respond. 

Also, if it's as easy as changing one tag, then why is it a big deal to implement it as a switch? Why is this *intended* behavior? This is so puzzling to me. If this is how Flathub wants to be, I can accept that, but at least some kind of *reasoning* would be helpful. Is there a HIG doc you could link to that explains why manual switching is bad? A discussion somewhere?

**Comment by razzeee** [comment]
It's not an accessibility issue, you're trying to change the framing. 

Look at every browser doc to find that they follow the system theme and that websites should respect that. Manual switching isn't bad per se. But we have no design for it and it shouldn't live on every page.

**Comment by s-20** [comment]
I don't see the point of arguing. You made your decision, and while I disagree with it, the web doesn't care what I think.

I will point out, though, that I'm not the one who initially pointed out that it's an accessibility issue. In this thread, someone else pointed it out first. I then agreed with them because this it why I actually care about this feature. Not being able to access dark mode because you choose to dodge fingerprinting is an accessibility issue. Period.

I flat out resent being accused of re-framing because I and another user listed the reason we wanted a feature. Work on it, don't work on it, I don't care, I can just use Gnome Software or Discover or whatever. But don't accuse me of moving the goalposts just because you couldn't be bothered to see where they were in the first place. 

SO here's my last question: do I discuss it being an accessibility issue here, or do I open an identical issue with a different reason? My initial issue didn't list a reason, so I don't see how it doesn't belong here for a discussion, but I can open a formal new issue if you'd prefer.

Or feel free to ban me, or whatever the Github equivalent is. I'm not sure I'm interested in dealing with this level of rudeness in any case.

**Comment by Atemo-C** [comment]
No matter what is being said, it seems as though this will never be implemented, to our detriment. It seems like adding things like a blur effect to loading elements are of a higher priority than a manual mode switching. But then again, this is not my website, and fortunately so, because I despise the modern web, and designing things for it.

I will now refrain from posting further comments on this closed issue, as it will bring us nowhere but towards an issue that is more and more toxic and unfriendly, which I do not want; Or it being locked, which is also not ideal.

I recommend you, @s-20, if you so want, to do the same, for I feel that it will not bring us any closer to a solution. I recommend to those who deal with the same issue as us to not bother either.

Farewell.
— Atemo

**Comment by SuperRicky14** [comment]
Sorry to revive a dead thread but I found a workaround for anyone unable to set their system dark mode. 

Paste this in your JavaScript console (usually accessed by F12 on most browsers):
```
localStorage.setItem('theme', 'dark');
window.location.reload();
```

And to go back to light theme:
```
localStorage.removeItem('theme');
window.location.reload();
```

Should remember your preference and switch immediately.
