### ISSUE TITLE
Saved cards need to handle bigger content

### ISSUE THREAD

**Issue by razzeee** [flathub/website#347]
![image](https://user-images.githubusercontent.com/5943908/172146057-741e0069-cfc9-4e2c-997f-cf763c6efe0b.png)

**Comment by kymckay** [comment]
Ah never mind I see it now, when the expiry date is double digit

**Comment by kymckay** [comment]
Thinking longer term, to improve maintainability and robustness (particularly with translation in mind) of the card related elements it may make sense to adopt a more list based UI structure (e.g. card selection during Amazon checkout). Possible benefits:

- It would be easier to populate in a content driven way instead of having to fit the content into a card-like element.
- It should be easier to adapt to varied screen sizes.
- It could enable tidier implementation of saved card related controls (e.g. expand row in list).

**Comment by razzeee** [comment]
FYI, I'll likely setup a storybook as soon as I can handle, so that we can test cases like this better.

**Comment by razzeee** [comment]
Oh, and while looking for some inspiration, I realized, that you tried to make this look like a credit card itself?

So maybe just sticking to that format and maybe getting rid of the labels might be enough.

https://bbbootstrap.com/snippets/tailwind-css-credit-card-template-33568462 might be a nice starting point

**Comment by razzeee** [comment]
I'm wondering if the flag is a hard requirement

**Comment by razzeee** [comment]
https://github.com/flathub/website/pull/640 will improve this to some degree
