### ISSUE TITLE
Some images are not hosted by flathub

### ISSUE THREAD

**Issue by razzeee** [flathub/website#49]
There seem to be some apps, that don't host their pictures on flathub. Probably apps, that can directly publish?
The icon here is an example https://flathub.org/apps/details/com.airtame.Client

Haven't found any more.

This is a problem, if we want to optimize the images in nextjs

**Comment by razzeee** [comment]
@barthalion this is ideally something we should get fixed before launching. any idea if that's something you can look into?

**Comment by barthalion** [comment]
We're not using Next.js image optimization after all. Does it still make sense to work on?

**Comment by razzeee** [comment]
We are right now, I just checked. That's also why https://beta.flathub.org/apps/details/com.airtame.Client for e.g. doesn't show a logo.

**Comment by razzeee** [comment]
Nevermind, we have a fallback for that, to opt out of the image tag. But our content security policy blocks the image. So the real reason to work on this, is to make the csp happy.

**Comment by ramcq** [comment]
I think we should either mirror these icons or require the URL to be a local one - there is no tradmark issue with storing somebody's logo/icon to refer to literally their software, we don't have any particular concern hosting the actual icons for the original software.

**Comment by wjt** [comment]
@GeorgesStavracas profiled Gnome Software recently and discovered that the bulk of the delay between clicking a category and the category page loading is spent downloading remote icons (iirc some of which are dead links, so they aren't even cached, so you pay the cost every time).

I didn't quite join the dots at the time but, while Gnome Software should probably be smarter since the appstream spec supports remote icons, maybe Flathub could just ban them, and then for Endless the problem would just go away?

**Comment by razzeee** [comment]
This should be solved with the recent appstream changes to libappstream, as it should be mirroring all icons as far as we know.
