### ISSUE TITLE
Home page: Multiple rows of apps per group

### ISSUE THREAD

**Issue by bertob** [flathub/website#502]
The home page layout doesn't feel great, because it's a bunch of headers + a single row of icons. I'd do at least 2 rows of icons per row, probably the easiest thing to do would be just doubling the number of items per category to 12.

![image](https://user-images.githubusercontent.com/1908896/180895731-54570dab-3f4b-440e-8659-bad09ad26ea8.png)

**Comment by razzeee** [comment]
I guess your happy with the smaller breakpoints then?  Should we truncate those, if we go for 12 items on the large one?

**Comment by bertob** [comment]
My feeling is 12 would work fine at all sizes, but we may want to make the cards smaller at those sizes. Maybe they could switch to a list row layout like in Software for mobile?

**Comment by razzeee** [comment]
They absolutely can. We should probably talk about expectations here. Since I asked in the designer channel at some point, it was suggested to have list row cards - as they better fit and show more of the summary. So I have been playing around with that some, but I thought we would replace them at all sizes.

Is there a size that one or the other is better? Or would we want to completely switch?

**Comment by bertob** [comment]
Switching to the horizontal layout everywhere also works :+1:

**Comment by razzeee** [comment]
Let's start with the 12 items change for now
