### ISSUE TITLE
Cannot get back after clicking 'Donate to Flathub'

### ISSUE THREAD

**Issue by q30a** [flathub/website#513]
1. Go to https://beta.flathub.org/ in private browsing mode.
2. Click 'Donate to Flathub'.
3. Try to go back either by clicking browser back button or swipe gesture.

Current result:
User is constantly redirected to https://beta.flathub.org/login?returnTo=%2Fdonate.

Expected result:
User is taken back to https://beta.flathub.org/

**Comment by kymckay** [comment]
Well found, I believe this may be as simple as using `router.replace` instead of `router.push` in the `LoginGuard` component. [Next.js docs here](https://nextjs.org/docs/api-reference/next/router#routerreplace).

What's happening is when redirected to the login page, a new entry is added to the history stack. So when you go back, you go back to the donate page which immediately redirects you to login again.
