### ISSUE TITLE
App page header: Actions are a mess

### ISSUE THREAD

**Issue by bertob** [flathub/website#536]
The buttons on the right side should be centered vertically on the content on the left:

![image](https://user-images.githubusercontent.com/1908896/182820789-578c8747-89d6-456f-b495-0dfb6ad75dd7.png)

**Comment by razzeee** [comment]
I agree in that case, but what happens, when the third button is shown there?

Hrm, looking at the code, it actually seems like ther could be up to four buttons. Not sure if that case really exists.

**Comment by bertob** [comment]
Can we just have all these buttons arranged horizontally next to each other (and on mobile a second row below the icon/name)? That'd both look nicer and resolve the layout problems with too many buttons.

**Comment by razzeee** [comment]
That part is a mess. I don't think we should have all of those buttons (there).
(there are also three primary buttons...)

But the latest PR improves it a bit.

**Comment by bertob** [comment]
Are you sure this should be closed? They're now next to each other, but they don't look centered vertically:

![image](https://user-images.githubusercontent.com/1908896/183415871-98a583dc-8082-45ad-b430-13e3b14500db.png)

**Comment by razzeee** [comment]
I thought, that with moving them to this layout, we wouldn't want them centered anymore. As that might mess up muscle memory when there are more then two buttons. I think that part needs design in general, but first thing would be figuring out, which buttons can really exist (or should exist)

@kymckay 

Currently we can show there
- Install
- Donate
- Developer Settings
- Purchase

I would think purchase and donate should exclude each other, but maybe not? At least they don't right now.

I understand where the developer settings button comes from, but I think it should be either moved or made into a textlink and be smaller and maybe in more of a background color.

**Comment by kymckay** [comment]
I had the same consideration for the purchase and donate buttons. The reason I chose not to make them exclusive is just because the existing Donate button is for external donation channels (as I understand it) and I was unsure what the plan is with regards to showing those vs prioritising payment/donation via Flathub itself.

And yeah your list is correct, though that last purchase button is conditionally a donate button too if the developer has their app set up for donations and no payment. Perhaps the other donation button should be moved elsewhere since it's not a Flathub related action?

**Comment by razzeee** [comment]
Superseded by https://github.com/flathub/website/issues/998
