### ISSUE TITLE
Draw all downloads over time monthly or weekly instead of daily

### ISSUE THREAD

**Issue by q30a** [flathub/website#538]
It is quite troublesome to read data from the image on https://beta.flathub.org/statistics. I think that by drawing the line on monthly or weekly basis instead of daily basis it would look a lot smoother and it would be easier to read

![image](https://user-images.githubusercontent.com/105132988/182847157-d1da6ed1-1a01-4182-a07b-4bfa1e297d2c.png)

**Comment by q30a** [comment]
Additional info: 
take a look at https://www.google.com/search?q=btc+to+usd
the granularity is depending on how much of chart is displayed:
if MAX is chosen, the line is drawn on weekly basis,
if 1Y is chosen, the line is drawn on daily basis,
if 1D is chosen, the line is drawn on 5 minute basis.

**Comment by kymckay** [comment]
I'll throw in that "Downloads over time" sounds cumulative, which I presume this isn't since the chart is not monotonic. Would this be better presented as "Daily/Weekly/Montly downloads" (respectively)?

**Comment by razzeee** [comment]
I'll close this, as we're only rendering the last 6 months now

**Comment by blendirapi** [comment]
@razzeee The site went back to showing all-time data at some point after this issue was closed. On mobile it's basically unusable.

Can we reopen this?  We've added over 3 more years of data (about 8 years total now). The chart is even harder to read than before. Monthly or even quarterly data would help a lot.

Here's a screenshot of how it looks today:

<img width="363" height="561" alt="Image" src="https://github.com/user-attachments/assets/2e168b2b-9fb9-437a-aab9-c3a95f6b47a7" />

<img width="1291" height="792" alt="Image" src="https://github.com/user-attachments/assets/cb2db5fb-4836-4a6a-b4ef-ff96cd2466c1" />
