### ISSUE TITLE
Redisinsight graph goes boom

### ISSUE THREAD

**Issue by razzeee** [flathub/website#965]
![Screenshot_20230126-073440_Firefox Nightly.png](https://user-images.githubusercontent.com/5943908/214772319-351bb423-b00e-42e1-87d8-692eeed31552.png)

**Comment by barthalion** [comment]
It was renamed, so I assume we're doing something wrong with stats.

**Comment by JakobDev** [comment]
> It was renamed, so I assume we're doing something wrong with stats.

The Backednd dind't notice the rename at the time of writing. It isin't listed in https://flathub.org/api/v2/eol/rebase. The problem is, that the respond of https://flathub.org/api/v2/stats/com.redis.RedisInsight currently looks like this:
```json
{
    "installs_total": 741,
    "installs_per_day": {
        "2023-01-24": 129,
        "2023-01-02": 21,
        "2023-01-03": 29,
        "2023-01-04": 27,
        "2023-01-05": 16,
        "2023-01-06": 31,
        "2023-01-07": 25,
        "2023-01-08": 31,
        "2023-01-09": 19,
        "2023-01-10": 37,
        "2023-01-11": 27,
        "2023-01-12": 22,
        "2023-01-13": 37,
        "2023-01-14": 17,
        "2023-01-15": 31,
        "2023-01-16": 12,
        "2023-01-17": 12,
        "2023-01-18": 27,
        "2023-01-19": 20,
        "2023-01-20": 27,
        "2023-01-21": 11,
        "2023-01-22": 19,
        "2023-01-23": 26
    },
    "installs_last_month": 741,
    "installs_last_7_days": 300
}
```
`2023-01-24 `comes for some reason first, was causes this Issue. Sorting the List should fix it. I can take a look at it when I have time.
